development:
  adapter: postgresql
  database: snippets_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: snippets_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: snippets_production
  pool: 5
  timeout: 5000
